apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor
  labels:
    app: flask-aws-monitor
spec:
  type: LoadBalancer
  selector:
    app: flask-aws-monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    name: http
