replicaCount: 2
image:
  repository: yourdockerhubuser/flask-app
  pullPolicy: IfNotPresent
  tag: latest
service:
  type: LoadBalancer
  port: 5001
ingress:
  enabled: false
env:
  AWS_ACCESS_KEY_ID: "<YOUR_KEY>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_SECRET>"
