apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-aws-monitor.fullname" . }}-aws-credentials
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.aws.secretAccessKey | quote }}
