apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-aws-monitor.fullname" . }}
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
spec:
  type: {{ include "flask-aws-monitor.serviceType" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flask-aws-monitor.selectorLabels" . | nindent 4 }}
